INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (1, 'ONNESTA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (2, 'LA PROTECTORA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (3, 'SABSA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (4, 'COBERTURA MÉDICA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (5, 'GRANDIA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (6, 'KUBRO', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (7, 'CONSORCIO MÉDICO', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (8, 'AVIZORA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (9, 'SEMEFA', 1, NULL, NOW());
INSERT INTO `companies` (`id`, `name`, `is_active`, `created_by`, `created_at`) VALUES (10, 'PROTECTA SECURITY', 1, NULL, NOW());
